import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MyFooter from "./Utils/MyFooter";
import Navbars from "./Utils/Navbars";
import { DrawerProvider } from "./Utils/DrawerContext";
import MiniDrawer from "./Utils/DrawerPatient/MyDrawer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Siwa Garden",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <DrawerProvider>
          <Navbars/>
          <MiniDrawer/>
            {children}
          <MyFooter/>
        </DrawerProvider>
      </body>
    </html>
  );
}
